### ISSUE TITLE
uninitialized constant Psych::ENGINE

### ISSUE THREAD

**Issue by tit** [josephwilk/pairwise#6]
```bash
$ gem list pairwise
pairwise (0.2.1)

$ cat test_data.yaml # example from documentation
event with image: [Football, Basketball, Soccer]
event without image: [Football, Basketball, Soccer]
media: [Image, Video, Music]

$ pairwise test_data.yaml 
/Users/tit/.rvm/gems/ruby-2.3.1/gems/pairwise-0.2.1/lib/pairwise.rb:16:in `<top (required)>': uninitialized constant Psych::ENGINE (NameError)
	from /Users/tit/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/tit/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/tit/.rvm/gems/ruby-2.3.1/gems/pairwise-0.2.1/bin/pairwise:4:in `<top (required)>'
	from /Users/tit/.rvm/gems/ruby-2.3.1/bin/pairwise:23:in `load'
	from /Users/tit/.rvm/gems/ruby-2.3.1/bin/pairwise:23:in `<main>'
	from /Users/tit/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/tit/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

What am I doing wrong?

**Comment by qbiak** [comment]
unsupported Ruby version, try with 2.1.8

**Comment by tit** [comment]
Thanx!
