### ISSUE TITLE
uninitialized constant Psych::ENGINE (NameError)

### ISSUE THREAD

**Issue by rsporny** [josephwilk/pairwise#7]
Hi,

running
`pairwise inputs.yml`
causes this error
`/usr/local/lib/ruby/gems/2.4.0/gems/pairwise-0.2.1/lib/pairwise.rb:16:in `<top (required)>': uninitialized constant Psych::ENGINE (NameError)
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/gems/2.4.0/gems/pairwise-0.2.1/bin/pairwise:4:in `<top (required)>'
	from /usr/local/bin/pairwise:22:in `load'
	from /usr/local/bin/pairwise:22:in `<main>'`

**Comment by rsporny** [comment]
Are you going to support newer Ruby versions?

**Comment by turboladen** [comment]
I'm getting this too.

**Comment by turboladen** [comment]
@rsporny looks like it works if I use master.

**Comment by Vishakha-singal** [comment]
I am getting this too. @turboladen I did not understand what you mean by using through master.

**Comment by turboladen** [comment]
@Vishakha-singal I mean that it works if I use the `master` branch from this repository.

**Comment by webdev36** [comment]
How can I solve this issue?
`NameError: uninitialized constant Psych::ENGINE`
ruby version is 2.5.3, rails version is 4.0.0
